---
# tasks file for httpd
- name: Install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/ansible/hosts/httpd/files/index1.html
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
